schema:
  - https://router.mirasys.dev/graphql:
      headers:
        Authorization: Bearer ${CODEGEN_TOKEN}

documents:
  - "src/**/*.graphql"

generates:
  src/core/gql/schema-types.ts:
    plugins: [ "typescript" ]
    config:
      useTypeImports: true
      enumsAsTypes: true
      defaultScalarType: unknown
      scalars:
        ID: string
        UUID: string
        DateTime: string

  src/core/gql/operations.ts:
    plugins: [ "typescript-operations", "typescript-react-apollo" ]
    config:
      withHooks: true
      reactApolloVersion: 3
      useTypeImports: true
      avoidOptionals: true
      immutableTypes: false
      dedupeOperationSuffix: true
      exportFragmentSpreadSubTypes: true
      preResolveTypes: false
      addDocBlocks: true
